title: Joshua | Full-Stack Developer
author: Joshua White
email: jwhite83193@gmail.com
description: >-
 Welcome to my portfolio site.

social:
  github: jwhite83193
  linkedin: joshua-white-92225536b

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
